### ISSUE TITLE
Command mediadc:collector:cleanup not working!

### ISSUE THREAD

**Issue by ondrejlohnisky** [andrey18106/mediadc#102]
I dont know how this command should behave. But It gives me an error after i use this command: 
``sudo -u www-data php occ mediadc:collector:cleanup``

The error:
```
An unhandled exception has been thrown:
Error: Call to a member function info() on null in /var/www/nextcloud/apps/mediadc/lib/Service/CleanupService.php:67
Stack trace:
#0 /var/www/nextcloud/apps/mediadc/lib/Command/CollectorCleanupCommand.php(54): OCA\MediaDC\Service\CleanupService->cleanup()
#1 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\MediaDC\Command\CollectorCleanupCommand->execute()
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#5 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#6 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#7 /var/www/nextcloud/occ(11): require_once('...')
#8 {main}%
```

**Comment by ondrejlohnisky** [comment]
I was able to make it run when i commented out line 67.

**Comment by ondrejlohnisky** [comment]
#103
