### ISSUE TITLE
syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /var/www/nextcloud/apps/mediadc/lib/Service/CollectorService.php:177

### ISSUE THREAD

**Issue by GrumpyMeow** [andrey18106/mediadc#13]
**Describe the bug**
Yesterday I've installed the mediadc-app in my Nextcloud installation just after i'd upgraded to v21.0.5. 
When i browse to my Nextcloud-web i receive an generic error screen.
To fix the error i tried to run: `sudo -u www-data php occ upgrade`

**To Reproduce**
1. Install mediadc app in Nextcloud v21.0.5
2. Run: sudo -u www-data php occ upgrade
3. See error in console

**Expected behavior**
I didn't expect to see an error about the Mediadc-app

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Proxmox VE 7, Turnkey LXC container
 - Nextcloud version: v21.0.5
 - MediaDC version: v0.1.0

**Additional context**
```
root@nextcloud .../www/nextcloud# sudo -u www-data php occ upgrade
An unhandled exception has been thrown:
ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /var/www/nextcloud/apps/mediadc/lib/Service/CollectorService.php:177
Stack trace:
#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/var/www/nextcl...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('OCA\\MediaDC\\Ser...')
#2 [internal function]: spl_autoload_call('OCA\\MediaDC\\Ser...')
#3 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(107): ReflectionClass->__construct('OCA\\MediaDC\\Ser...')
#4 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\MediaDC\\Ser...')
#5 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query('OCA\\MediaDC\\Ser...')
#6 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(431): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\MediaDC\\Ser...')
#7 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\MediaDC\\Ser...', true)
#8 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#9 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): array_map(Object(Closure), Array)
#10 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#11 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\MediaDC\\Com...')
#12 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query('OCA\\MediaDC\\Com...')
#13 /var/www/nextcloud/lib/private/ServerContainer.php(146): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\MediaDC\\Com...')
#14 /var/www/nextcloud/lib/private/Console/Application.php(221): OC\ServerContainer->query('OCA\\MediaDC\\Com...')
#15 /var/www/nextcloud/lib/private/Console/Application.php(136): OC\Console\Application->loadCommandsFromInfoXml(Array)
#16 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
```
```
#18 {main}root@nextcloud .../www/nextcloud# php -v
PHP 7.3.29-1~deb10u1 (cli) (built: Jul  2 2021 04:04:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.29, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.29-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by andrey18106** [comment]
Hi, thanks for your bug report.

That syntax error occurred because we are using some new PHP features that are available since PHP version 7.4 (that is described in requirements [here](https://github.com/andrey18106/mediadc/wiki/Installation). So you should upgrade your PHP to 7.4 or higher.

May be we'll rewrite code to support PHP 7.3 in a future updates.

**Comment by bigcat88** [comment]
Good catch, we missed php dependency in app/info.xml file with required version.
