### ISSUE TITLE
MediaDC fails to install

### ISSUE THREAD

**Issue by GewoonYorick** [andrey18106/mediadc#29]
**Describe the bug**
MediaDC fails to install and throws the error down below.

**To Reproduce**
1. Run the install command / install through the store. (`occ app:install mediadc`)
2. Get an error:
```php
Illegal instruction (core dumped)
An unhandled exception has been thrown:
TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/custom_apps/mediadc/lib/Service/PythonService.php:357
Stack trace:
#0 /var/www/html/custom_apps/mediadc/lib/Service/PythonService.php(357): count(NULL)
#1 /var/www/html/custom_apps/mediadc/lib/Service/PythonService.php(153): OCA\MediaDC\Service\PythonService->parsePythonOutput(Array)
#2 /var/www/html/custom_apps/mediadc/lib/Migration/AppUpdateStep.php(72): OCA\MediaDC\Service\PythonService->installDependencies('required option...')
#3 /var/www/html/lib/private/Repair.php(123): OCA\MediaDC\Migration\AppUpdateStep->run(Object(OC\Repair))
#4 /var/www/html/lib/private/legacy/OC_App.php(1059): OC\Repair->run()
#5 /var/www/html/lib/private/Installer.php(149): OC_App::executeRepairSteps('mediadc', Array)
#6 /var/www/html/core/Command/App/Install.php(75): OC\Installer->installApp('mediadc', false)
#7 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/console.php(99): OC\Console\Application->run()
#13 /var/www/html/occ(11): require_once('/var/www/html/c...')
#14 {main}
```

**Expected behavior**
I expect the app to install without problems.

**Server:**
 - Docker: nextcloud:22.2.0
 - CPU x64
 - Nextcloud version: 22.2.0

**Comment by GewoonYorick** [comment]
That docker nextcloud image uses PHP8 :)

**Comment by bigcat88** [comment]
@GewoonYorick 
Can you remove hexhamming module? Look it wiki how to do so, we will release update soon(in a few days).
If you have any questions or it will not help, just write here or to telegram chat.

**Comment by GewoonYorick** [comment]
I've removed hexhamming, issue still persist.

**Comment by bigcat88** [comment]
@GewoonYorick you check 0.1.8 version and say if something was changed.

**Comment by GewoonYorick** [comment]
The error log has changed a bit:
```php
occ app:install mediadc
An unhandled exception has been thrown:
TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/custom_apps/mediadc/lib/Migration/AppUpdateStep.php:69
Stack trace:
#0 /var/www/html/custom_apps/mediadc/lib/Migration/AppUpdateStep.php(69): count(NULL)
#1 /var/www/html/lib/private/Repair.php(123): OCA\MediaDC\Migration\AppUpdateStep->run(Object(OC\Repair))
#2 /var/www/html/lib/private/legacy/OC_App.php(1070): OC\Repair->run()
#3 /var/www/html/lib/private/Installer.php(148): OC_App::executeRepairSteps('mediadc', Array)
#4 /var/www/html/core/Command/App/Install.php(75): OC\Installer->installApp('mediadc', false)
#5 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/console.php(99): OC\Console\Application->run()
#11 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

**Comment by bigcat88** [comment]
@GewoonYorick Can you disable+remove MediaDC, then drop all MediaDC tables and it's record from `migrations` tables and repeat install?
MediaDC tables: oc_mediadc_photos , oc_mediadc_settings , oc_mediadc_tasks , oc_mediadc_tasks_details , oc_mediadc_videos
`DROP TABLE oc_mediadc_photos, oc_mediadc_settings, oc_mediadc_tasks, oc_mediadc_tasks_details, oc_mediadc_videos;`
Migration record are in table `oc_migrations`, where `app = mediadc` if you with to delete it by hans, or here is a request:
`DELETE FROM oc_migrations WHERE app='mediadc';`

If you have non standart table prefix, replace `oc_` with yours.

**Comment by GewoonYorick** [comment]
I've removed mediadc, confirmed it was removed.
Dropped the tables above, and confirmed that they were dropped.
Removed the migration record for mediadc, and confirmed that it was removed.

After that I ran the install command again: 
```php
php occ app:install mediadc
mediadc 0.1.8 installed
An unhandled exception has been thrown:
TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/custom_apps/mediadc/lib/Migration/AppUpdateStep.php:69
Stack trace:
#0 /var/www/html/custom_apps/mediadc/lib/Migration/AppUpdateStep.php(69): count(NULL)
#1 /var/www/html/lib/private/Repair.php(123): OCA\MediaDC\Migration\AppUpdateStep->run(Object(OC\Repair))
#2 /var/www/html/lib/private/legacy/OC_App.php(1070): OC\Repair->run()
#3 /var/www/html/lib/private/Installer.php(148): OC_App::executeRepairSteps('mediadc', Array)
#4 /var/www/html/lib/private/legacy/OC_App.php(439): OC\Installer->installApp('mediadc')
#5 /var/www/html/core/Command/App/Install.php(91): OC_App->enable('mediadc')
#6 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/console.php(99): OC\Console\Application->run()
#12 /var/www/html/occ(11): require_once('/var/www/html/c...')
#13 {main}
```

**Comment by andrey18106** [comment]
Did you tried install MediaDC via GUI? Seems like that's my flaw, there should additional not-null-check.

**Comment by andrey18106** [comment]
@GewoonYorick Reproduced this error.

If you want finally use MediaDC now, you can change [69 line of code](https://github.com/andrey18106/mediadc/blob/main/lib/Migration/AppUpdateStep.php#L69) from `if (count($installed['not_installed_list']['boost']) > 0) {` to `if (isset($installed['not_installed_list']['boost']) && count($installed['not_installed_list']['boost']) > 0) {`.  

Let us know what the results on your NC instance with this change if you'll try.

We will update current release or in the next 0.1.9 version with this bug fix, thank you for you feedback.

**Comment by GewoonYorick** [comment]
Hi there,

I've applied the suggested change and it installs and enables mediadc without errors now. 

Thank you for your help :)

**Comment by andrey18106** [comment]
Updated latest release (0.1.8) with this bug fix. Closing issue.
